# -*- coding: utf-8 -*-
"""Elevator_problem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12dUnXdCRCA3iVRTV9JLtlex85HDc0cpT
"""

from collections import deque

def elevator_problem(start, goal, total_floors, blocked_floors=None):
    if blocked_floors is None:
        blocked_floors = set()
    else:
        blocked_floors = set(blocked_floors)

    # Queue stores: (current_floor, path_taken)
    queue = deque([(start, [start])])

    # Keep track of visited floors
    visited = {start}

    while queue:
        current_floor, path = queue.popleft()

        # Goal reached
        if current_floor == goal:
            return path

        # Possible movements: down and up
        next_floors = [
            current_floor - 1,
            current_floor + 1
        ]

        for next_floor in next_floors:

            # Check floor boundaries
            if next_floor < 1 or next_floor > total_floors:
                continue

            # Check blocked floors
            if next_floor in blocked_floors:
                continue

            # Check whether already visited
            if next_floor in visited:
                continue

            visited.add(next_floor)

            new_path = path + [next_floor]
            queue.append((next_floor, new_path))

    return None


# -----------------------------
# Example
# -----------------------------

total_floors = 10
start_floor = 1
goal_floor = 8

# Remove blocked_floors to show a working path
# blocked_floors = [4, 6]

path = elevator_problem(
    start_floor,
    goal_floor,
    total_floors,
    # blocked_floors
)

if path:
    print("Elevator Path:")
    print(" → ".join(map(str, path)))

    print("\nNumber of moves:", len(path) - 1)
else:
    print("No path found.")